### ISSUE TITLE
Support text sharing

### ISSUE THREAD

**Issue by wanderseeme** [cowbell/sharedrop#86] opened 2020-03-24 15:56 UTC
Please add a feature of text sharing, e.g., right-click on an icon to popup a text sharing message box to share.
This feature is inspired by Snapdrop (https://snapdrop.net/).

**Comment by nashbridges** [comment] 2020-06-09 18:07
This is a duplicate of https://github.com/cowbell/sharedrop/issues/80.

**Comment by szimek** [comment] 2020-07-20 06:04
I'm closing this one as a duplicate of #80.

**Closed by szimek** 2020-07-20 06:04 UTC
Labels: enhancement

**Comment by ethanneff** [comment] 2024-07-31 22:08
use https://snapdrop.net/ instead. can share files and text
